In [1]:
import pandas as pd
import numpy as np

In [3]:
array_1D = np.array([1,2,3])

array_2D = np.array([(1,2,3),(4,5,6)])

In [4]:
array_1D

array([1, 2, 3])

In [5]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
np.empty(1)

array([1.])

In [13]:
np.random.random(5)

array([0.68657743, 0.2317476 , 0.09120684, 0.19182017, 0.40394523])

In [15]:
np.random.randint(5,10)

6

In [16]:
array_2D.shape

(2, 3)

In [17]:
array_2D.ndim

2

In [ ]:
array_2D.size # 2 * 3

6

In [19]:
array_2D.dtype

dtype('int64')

In [21]:
array_float = np.array([2,6,8], dtype=np.float64)
array_float.dtype

dtype('float64')

In [22]:
array = np.array([2,3,57,1,368,37,8,9,3,5])

array[3]

np.int64(1)

In [24]:
array[-1]

np.int64(5)

In [25]:
array[-1] = 42
array

array([  2,   3,  57,   1, 368,  37,   8,   9,   3,  42])

In [26]:
array[0:3]

array([ 2,  3, 57])

In [27]:
array_2D[:1, 1:2]


array([[2]])

In [28]:
array[::-1]

array([ 42,   3,   9,   8,  37, 368,   1,  57,   3,   2])

In [29]:
mask = array > 20

array[mask]

array([ 57, 368,  37,  42])

## Exercícios

In [30]:
arr = np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
mat = arr.reshape((3,5))
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
print("Shape: ", mat.shape, "| dtype: ", mat.dtype)

Shape:  (3, 5) | dtype:  int64


In [34]:
arr = np.arange(0, 21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [35]:
arr[9:16] *= -1

arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [36]:
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [37]:
mask = arr % 3 == 0
arr[mask]

array([ 0,  3,  6,  9, 12, 15, 18])