In [1]:
import pandas as pd
import numpy as np

In [3]:
array_1D = np.array([1,2,3])

array_2D = np.array([(1,2,3),(4,5,6)])

In [4]:
array_1D

array([1, 2, 3])

In [5]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
np.empty(1)

array([1.])

In [13]:
np.random.random(5)

array([0.68657743, 0.2317476 , 0.09120684, 0.19182017, 0.40394523])

In [15]:
np.random.randint(5,10)

6

In [16]:
array_2D.shape

(2, 3)

In [17]:
array_2D.ndim

2

In [ ]:
array_2D.size # 2 * 3

6

In [19]:
array_2D.dtype

dtype('int64')

In [21]:
array_float = np.array([2,6,8], dtype=np.float64)
array_float.dtype

dtype('float64')